export const prerender = true;

export function GET() {
  const body = [
    "# Markdown Knowledge Graph agent primer",
    "",
    "Markdown Knowledge Graph (mdkg) is git-native project memory for AI coding agents and AI-native software engineering.",
    "",
    "## What mdkg is",
    "",
    "- a local-first CLI",
    "- a Markdown + frontmatter graph",
    "- a deterministic context-pack builder",
    "- a goal/task/spike/checkpoint lifecycle tool",
    "- an agent handoff tool",
    "- a validation and repair aid",
    "- an advanced alpha substrate for subgraphs, bundles, workflow mirrors, read-only MCP, and local queue workflows",
    "",
    "## What mdkg is not",
    "",
    "- not an autonomous coding agent",
    "- not an autonomous execution runtime",
    "- not a hosted memory service",
    "- not a vector database",
    "- not a daemon",
    "- not a comprehensive secret scanner",
    "- not a production queue/event ledger",
    "",
    "## Canonical agent path",
    "",
    "1. Read AGENT_START.md.",
    "2. Run mdkg status.",
    "3. Inspect the current goal with mdkg goal current.",
    "4. Run mdkg goal next.",
    "5. Show and pack one work node with mdkg show WORK_ID and mdkg pack WORK_ID.",
    "6. Do work outside mdkg.",
    "7. Record evidence with checkpoints, handoffs, or task updates.",
    "8. Validate with mdkg validate before closeout.",
    "",
    "## Plan -> Work -> Evidence",
    "",
    "- Plan: read repo guidance, inspect graph state, and choose one bounded work node.",
    "- Work: claim the node only when mutating lifecycle state, then make changes outside mdkg.",
    "- Evidence: run checks, record proof, create a checkpoint or handoff, and validate before closeout.",
    "",
    "## Core commands",
    "",
    "- mdkg init --agent",
    "- mdkg index",
    "- mdkg status",
    "- mdkg validate",
    "- mdkg search <query>",
    "- mdkg show WORK_ID",
    "- mdkg goal current",
    "- mdkg goal next",
    "- mdkg goal claim GOAL_ID WORK_ID",
    "- mdkg pack WORK_ID",
    "- mdkg handoff create WORK_ID",
    "- mdkg task done TASK_ID --checkpoint \"Meaningful milestone\"",
    "",
    "## Safety boundaries",
    "",
    "Do not store these in mdkg nodes, packs, checkpoints, or handoffs:",
    "",
    "- raw secrets",
    "- tokens",
    "- private keys",
    "- provider payloads",
    "- unredacted prompt text",
    "- private graph dumps",
    "- bulky runtime traces",
    "",
    "Handoff raw-marker warnings and no-secret checks are safety aids, not comprehensive data-loss prevention.",
    "",
    "## Agent-readable paths",
    "",
    "- /quickstart",
    "- /trust",
    "- /alpha",
    "- https://docs.mdkg.dev/",
    "- /llms.txt",
    "- /llms-full.txt",
    "- /sitemap.xml",
    "",
    "Use the generated CLI reference from docs/_generated/cli-reference.md when working from the repository source.",
    "",
  ].join("\n");

  return new Response(body, {
    headers: {
      "content-type": "text/plain; charset=utf-8"
    }
  });
}
