const HELP_TARGETS = [
  ["global"],
  ["init"],
  ["upgrade"],
  ["new"],
  ["show"],
  ["list"],
  ["search"],
  ["pack"],
  ["handoff"],
  ["capability"],
  ["capability", "list"],
  ["capability", "search"],
  ["capability", "show"],
  ["spec"],
  ["spec", "list"],
  ["spec", "show"],
  ["spec", "validate"],
  ["archive"],
  ["archive", "add"],
  ["archive", "list"],
  ["archive", "show"],
  ["archive", "verify"],
  ["archive", "compress"],
  ["bundle"],
  ["bundle", "create"],
  ["bundle", "list"],
  ["bundle", "show"],
  ["bundle", "verify"],
  ["bundle", "import"],
  ["graph"],
  ["graph", "clone"],
  ["graph", "fork"],
  ["graph", "import-template"],
  ["graph", "refs"],
  ["subgraph"],
  ["subgraph", "add"],
  ["subgraph", "list"],
  ["subgraph", "show"],
  ["subgraph", "rm"],
  ["subgraph", "enable"],
  ["subgraph", "disable"],
  ["subgraph", "verify"],
  ["subgraph", "refresh"],
  ["subgraph", "sync"],
  ["subgraph", "materialize"],
  ["work"],
  ["work", "contract"],
  ["work", "trigger"],
  ["work", "order"],
  ["work", "receipt"],
  ["work", "artifact"],
  ["work", "validate"],
  ["goal"],
  ["goal", "show"],
  ["goal", "select"],
  ["goal", "activate"],
  ["goal", "current"],
  ["goal", "clear"],
  ["goal", "next"],
  ["goal", "claim"],
  ["goal", "evaluate"],
  ["goal", "pause"],
  ["goal", "resume"],
  ["goal", "done"],
  ["goal", "archive"],
  ["skill"],
  ["skill", "new"],
  ["skill", "list"],
  ["skill", "show"],
  ["skill", "search"],
  ["skill", "validate"],
  ["skill", "sync"],
  ["task"],
  ["task", "start"],
  ["task", "update"],
  ["task", "done"],
  ["event"],
  ["event", "enable"],
  ["event", "append"],
  ["next"],
  ["checkpoint"],
  ["validate"],
  ["status"],
  ["mcp"],
  ["mcp", "serve"],
  ["fix"],
  ["fix", "plan"],
  ["fix", "apply"],
  ["fix", "ids"],
  ["format"],
  ["doctor"],
  ["workspace"],
  ["db"],
  ["db", "index"],
  ["db", "queue"],
  ["db", "snapshot"],
  ["index"],
  ["guide"],
];

function helpTargetKey(target) {
  return target.join(" ");
}

module.exports = {
  HELP_TARGETS,
  helpTargetKey,
};
