import path from "path";
import { writeFile } from "./fs";

const DEFAULT_TEMPLATES: Record<string, string> = {
  task: [
    "---",
    "id: {{id}}",
    "type: task",
    "title: {{title}}",
    "status: {{status}}",
    "priority: {{priority}}",
    "epic: {{epic}}",
    "parent: {{parent}}",
    "prev: {{prev}}",
    "next: {{next}}",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "blocked_by: []",
    "blocks: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  bug: [
    "---",
    "id: {{id}}",
    "type: bug",
    "title: {{title}}",
    "status: {{status}}",
    "priority: {{priority}}",
    "epic: {{epic}}",
    "parent: {{parent}}",
    "prev: {{prev}}",
    "next: {{next}}",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "blocked_by: []",
    "blocks: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  feat: [
    "---",
    "id: {{id}}",
    "type: feat",
    "title: {{title}}",
    "status: {{status}}",
    "priority: {{priority}}",
    "epic: {{epic}}",
    "parent: {{parent}}",
    "prev: {{prev}}",
    "next: {{next}}",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "blocked_by: []",
    "blocks: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  epic: [
    "---",
    "id: {{id}}",
    "type: epic",
    "title: {{title}}",
    "status: {{status}}",
    "priority: {{priority}}",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "blocked_by: []",
    "blocks: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  chk: [
    "---",
    "id: {{id}}",
    "type: checkpoint",
    "title: {{title}}",
    "status: {{status}}",
    "priority: {{priority}}",
    "epic: {{epic}}",
    "parent: {{parent}}",
    "prev: {{prev}}",
    "next: {{next}}",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "blocked_by: []",
    "blocks: []",
    "refs: []",
    "aliases: []",
    "scope: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  prd: [
    "---",
    "id: {{id}}",
    "type: prd",
    "title: {{title}}",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  edd: [
    "---",
    "id: {{id}}",
    "type: edd",
    "title: {{title}}",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  dec: [
    "---",
    "id: {{id}}",
    "type: dec",
    "title: {{title}}",
    "status: proposed",
    "supersedes: {{supersedes}}",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  prop: [
    "---",
    "id: {{id}}",
    "type: prop",
    "title: {{title}}",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  rule: [
    "---",
    "id: {{id}}",
    "type: rule",
    "title: {{title}}",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
};

export function writeDefaultTemplates(root: string): void {
  for (const [name, content] of Object.entries(DEFAULT_TEMPLATES)) {
    writeFile(path.join(root, ".mdkg", "templates", "default", `${name}.md`), content);
  }
}
