import path from "path";
import { writeFile } from "./fs";

const DEFAULT_TEMPLATES: Record<string, string> = {
  task: [
    "---",
    "id: {{id}}",
    "type: task",
    "title: {{title}}",
    "status: {{status}}",
    "priority: {{priority}}",
    "epic: {{epic}}",
    "parent: {{parent}}",
    "prev: {{prev}}",
    "next: {{next}}",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "blocked_by: []",
    "blocks: []",
    "refs: []",
    "aliases: []",
    "skills: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  bug: [
    "---",
    "id: {{id}}",
    "type: bug",
    "title: {{title}}",
    "status: {{status}}",
    "priority: {{priority}}",
    "epic: {{epic}}",
    "parent: {{parent}}",
    "prev: {{prev}}",
    "next: {{next}}",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "blocked_by: []",
    "blocks: []",
    "refs: []",
    "aliases: []",
    "skills: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  test: [
    "---",
    "id: {{id}}",
    "type: test",
    "title: {{title}}",
    "status: {{status}}",
    "priority: {{priority}}",
    "epic: {{epic}}",
    "parent: {{parent}}",
    "prev: {{prev}}",
    "next: {{next}}",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "blocked_by: []",
    "blocks: []",
    "refs: []",
    "aliases: []",
    "skills: []",
    "cases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  feat: [
    "---",
    "id: {{id}}",
    "type: feat",
    "title: {{title}}",
    "status: {{status}}",
    "priority: {{priority}}",
    "epic: {{epic}}",
    "parent: {{parent}}",
    "prev: {{prev}}",
    "next: {{next}}",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "blocked_by: []",
    "blocks: []",
    "refs: []",
    "aliases: []",
    "skills: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  epic: [
    "---",
    "id: {{id}}",
    "type: epic",
    "title: {{title}}",
    "status: {{status}}",
    "priority: {{priority}}",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "blocked_by: []",
    "blocks: []",
    "refs: []",
    "aliases: []",
    "skills: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  chk: [
    "---",
    "id: {{id}}",
    "type: checkpoint",
    "title: {{title}}",
    "status: {{status}}",
    "priority: {{priority}}",
    "epic: {{epic}}",
    "parent: {{parent}}",
    "prev: {{prev}}",
    "next: {{next}}",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "blocked_by: []",
    "blocks: []",
    "refs: []",
    "aliases: []",
    "skills: []",
    "scope: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  prd: [
    "---",
    "id: {{id}}",
    "type: prd",
    "title: {{title}}",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  edd: [
    "---",
    "id: {{id}}",
    "type: edd",
    "title: {{title}}",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  dec: [
    "---",
    "id: {{id}}",
    "type: dec",
    "title: {{title}}",
    "status: proposed",
    "supersedes: {{supersedes}}",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  prop: [
    "---",
    "id: {{id}}",
    "type: prop",
    "title: {{title}}",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  spec: [
    "---",
    "id: {{id}}",
    "type: spec",
    "title: {{title}}",
    "version: 0.1.0",
    "role: subagent",
    "runtime_mode: room_orchestrated",
    "work_contracts: []",
    "requested_capabilities: []",
    "skill_refs: []",
    "tool_refs: []",
    "model_refs: []",
    "wasm_component_refs: []",
    "runtime_image_refs: []",
    "subagent_refs: []",
    "resource_profile: builder",
    "update_policy: manual",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  work: [
    "---",
    "id: {{id}}",
    "type: work",
    "title: {{title}}",
    "version: 0.1.0",
    "agent_id: agent.example",
    "kind: generic",
    "pricing_model: quoted",
    "required_capabilities: []",
    "skill_refs: []",
    "tool_refs: []",
    "model_refs: []",
    "wasm_component_refs: []",
    "runtime_image_refs: []",
    "subagent_refs: []",
    "inputs: [request:text:required]",
    "outputs: [result:text:required]",
    "receipt_required: true",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  work_order: [
    "---",
    "id: {{id}}",
    "type: work_order",
    "title: {{title}}",
    "version: 0.1.0",
    "work_id: work.example",
    "work_version: 0.1.0",
    "requester: user.example",
    "order_status: submitted",
    "request_ref: request.example",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  receipt: [
    "---",
    "id: {{id}}",
    "type: receipt",
    "title: {{title}}",
    "version: 0.1.0",
    "work_order_id: order.example",
    "receipt_status: recorded",
    "outcome: success",
    "cost_ref: cost.redacted",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  feedback: [
    "---",
    "id: {{id}}",
    "type: feedback",
    "title: {{title}}",
    "version: 0.1.0",
    "target_id: work.example",
    "sentiment: neutral",
    "feedback_status: new",
    "source_ref: user.example",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  dispute: [
    "---",
    "id: {{id}}",
    "type: dispute",
    "title: {{title}}",
    "version: 0.1.0",
    "work_order_id: order.example",
    "receipt_id: receipt.example",
    "dispute_status: open",
    "severity: medium",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  proposal: [
    "---",
    "id: {{id}}",
    "type: proposal",
    "title: {{title}}",
    "version: 0.1.0",
    "target_id: work.example",
    "proposal_status: proposed",
    "proposal_kind: work_update",
    "evidence_refs: []",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  rule: [
    "---",
    "id: {{id}}",
    "type: rule",
    "title: {{title}}",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
};

export function writeDefaultTemplates(root: string): void {
  for (const [name, content] of Object.entries(DEFAULT_TEMPLATES)) {
    writeFile(path.join(root, ".mdkg", "templates", "default", `${name}.md`), content);
  }
}
