import path from "path";
import { writeFile } from "./fs";

const DEFAULT_TEMPLATES: Record<string, string> = {
  task: [
    "---",
    "id: {{id}}",
    "type: task",
    "title: {{title}}",
    "status: {{status}}",
    "priority: {{priority}}",
    "epic: {{epic}}",
    "parent: {{parent}}",
    "prev: {{prev}}",
    "next: {{next}}",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "blocked_by: []",
    "blocks: []",
    "refs: []",
    "context_refs: []",
    "evidence_refs: []",
    "aliases: []",
    "skills: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  bug: [
    "---",
    "id: {{id}}",
    "type: bug",
    "title: {{title}}",
    "status: {{status}}",
    "priority: {{priority}}",
    "epic: {{epic}}",
    "parent: {{parent}}",
    "prev: {{prev}}",
    "next: {{next}}",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "blocked_by: []",
    "blocks: []",
    "refs: []",
    "context_refs: []",
    "evidence_refs: []",
    "aliases: []",
    "skills: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  spike: [
    "---",
    "id: {{id}}",
    "type: spike",
    "title: {{title}}",
    "status: {{status}}",
    "priority: {{priority}}",
    "epic: {{epic}}",
    "parent: {{parent}}",
    "prev: {{prev}}",
    "next: {{next}}",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "blocked_by: []",
    "blocks: []",
    "refs: []",
    "context_refs: []",
    "evidence_refs: []",
    "aliases: []",
    "skills: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
    "",
    "# Research Question",
    "",
    "# Search Plan",
    "",
    "# Findings",
    "",
    "# Recommendation",
    "",
    "# Follow-Up Nodes To Create",
    "",
    "# Skill Candidates",
    "",
    "# Evidence And Sources",
  ].join("\n"),
  test: [
    "---",
    "id: {{id}}",
    "type: test",
    "title: {{title}}",
    "status: {{status}}",
    "priority: {{priority}}",
    "epic: {{epic}}",
    "parent: {{parent}}",
    "prev: {{prev}}",
    "next: {{next}}",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "blocked_by: []",
    "blocks: []",
    "refs: []",
    "context_refs: []",
    "evidence_refs: []",
    "aliases: []",
    "skills: []",
    "cases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  feat: [
    "---",
    "id: {{id}}",
    "type: feat",
    "title: {{title}}",
    "status: {{status}}",
    "priority: {{priority}}",
    "epic: {{epic}}",
    "parent: {{parent}}",
    "prev: {{prev}}",
    "next: {{next}}",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "blocked_by: []",
    "blocks: []",
    "refs: []",
    "context_refs: []",
    "evidence_refs: []",
    "aliases: []",
    "skills: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  epic: [
    "---",
    "id: {{id}}",
    "type: epic",
    "title: {{title}}",
    "status: {{status}}",
    "priority: {{priority}}",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "blocked_by: []",
    "blocks: []",
    "refs: []",
    "context_refs: []",
    "evidence_refs: []",
    "aliases: []",
    "skills: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  chk: [
    "---",
    "id: {{id}}",
    "type: checkpoint",
    "title: {{title}}",
    "checkpoint_kind: {{checkpoint_kind}}",
    "status: {{status}}",
    "priority: {{priority}}",
    "epic: {{epic}}",
    "parent: {{parent}}",
    "prev: {{prev}}",
    "next: {{next}}",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "blocked_by: []",
    "blocks: []",
    "refs: []",
    "context_refs: []",
    "evidence_refs: []",
    "aliases: []",
    "skills: []",
    "scope: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  prd: [
    "---",
    "id: {{id}}",
    "type: prd",
    "title: {{title}}",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  edd: [
    "---",
    "id: {{id}}",
    "type: edd",
    "title: {{title}}",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  dec: [
    "---",
    "id: {{id}}",
    "type: dec",
    "title: {{title}}",
    "status: proposed",
    "supersedes: {{supersedes}}",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  prop: [
    "---",
    "id: {{id}}",
    "type: prop",
    "title: {{title}}",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  goal: [
    "---",
    "id: {{id}}",
    "type: goal",
    "title: {{title}}",
    "status: {{status}}",
    "priority: {{priority}}",
    "goal_state: {{goal_state}}",
    "goal_condition: {{goal_condition}}",
    "scope_refs: []",
    "active_node: {{active_node}}",
    "last_active_node: {{last_active_node}}",
    "required_skills: []",
    "required_checks: []",
    "max_iterations: {{max_iterations}}",
    "blocked_after_attempts: {{blocked_after_attempts}}",
    "epic: {{epic}}",
    "parent: {{parent}}",
    "prev: {{prev}}",
    "next: {{next}}",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "blocked_by: []",
    "blocks: []",
    "refs: []",
    "context_refs: []",
    "evidence_refs: []",
    "aliases: []",
    "skills: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  spec: [
    "---",
    "id: {{id}}",
    "type: spec",
    "title: {{title}}",
    "version: 0.1.0",
    "spec_kind: capability",
    "role: tool_service",
    "runtime_mode: tool_service",
    "work_contracts: []",
    "contract_profile: generic",
    "validation_policy_ref: policy.validation.default",
    "evidence_policy_ref: policy.evidence.default",
    "requested_capabilities: []",
    "skill_refs: []",
    "tool_refs: []",
    "model_refs: []",
    "wasm_component_refs: []",
    "runtime_image_refs: []",
    "subagent_refs: []",
    "resource_profile: local_cli",
    "update_policy: manual",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  manifest: [
    "---",
    "id: {{id}}",
    "type: manifest",
    "title: {{title}}",
    "version: 0.1.0",
    "spec_kind: capability",
    "role: tool_service",
    "runtime_mode: tool_service",
    "work_contracts: []",
    "contract_profile: generic",
    "validation_policy_ref: policy.validation.default",
    "evidence_policy_ref: policy.evidence.default",
    "requested_capabilities: []",
    "skill_refs: []",
    "tool_refs: []",
    "model_refs: []",
    "wasm_component_refs: []",
    "runtime_image_refs: []",
    "subagent_refs: []",
    "resource_profile: local_cli",
    "update_policy: manual",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  work: [
    "---",
    "id: {{id}}",
    "type: work",
    "title: {{title}}",
    "version: 0.1.0",
    "agent_id: agent.example",
    "kind: generic",
    "contract_profile: generic",
    "pricing_model: quoted",
    "required_capabilities: [capability.example]",
    "skill_refs: []",
    "tool_refs: []",
    "model_refs: []",
    "wasm_component_refs: []",
    "runtime_image_refs: []",
    "subagent_refs: []",
    "inputs: [request:text:required]",
    "outputs: [result:text:required]",
    "receipt_required: true",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  work_order: [
    "---",
    "id: {{id}}",
    "type: work_order",
    "title: {{title}}",
    "version: 0.1.0",
    "work_id: work.example",
    "work_version: 0.1.0",
    "requester: user.example",
    "order_status: submitted",
    "request_ref: request.example",
    "trigger_ref: trigger.manual",
    "payload_hash: sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "contract_profile: generic",
    "validation_policy_ref: policy.validation.default",
    "evidence_policy_ref: policy.evidence.default",
    "input_refs: []",
    "queue_refs: []",
    "requested_outputs: [result:text:required]",
    "constraint_refs: []",
    "artifact_policy: commit_sidecar_and_zip",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  receipt: [
    "---",
    "id: {{id}}",
    "type: receipt",
    "title: {{title}}",
    "version: 0.1.0",
    "work_order_id: order.example",
    "receipt_status: recorded",
    "outcome: success",
    "cost_ref: cost.redacted",
    "redaction_policy: refs_and_hashes_only",
    "contract_profile: generic",
    "receipt_kind: worker",
    "redaction_class: internal",
    "validation_policy_ref: policy.validation.default",
    "evidence_policy_ref: policy.evidence.default",
    "proof_refs: []",
    "attestation_refs: []",
    "evidence_hashes: []",
    "input_hashes: []",
    "output_hashes: []",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  feedback: [
    "---",
    "id: {{id}}",
    "type: feedback",
    "title: {{title}}",
    "version: 0.1.0",
    "target_id: work.example",
    "sentiment: neutral",
    "feedback_status: new",
    "source_ref: user.example",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  dispute: [
    "---",
    "id: {{id}}",
    "type: dispute",
    "title: {{title}}",
    "version: 0.1.0",
    "work_order_id: order.example",
    "receipt_id: receipt.example",
    "dispute_status: open",
    "severity: medium",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  proposal: [
    "---",
    "id: {{id}}",
    "type: proposal",
    "title: {{title}}",
    "version: 0.1.0",
    "target_id: work.example",
    "proposal_status: proposed",
    "proposal_kind: work_update",
    "evidence_refs: []",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  archive: [
    "---",
    "id: {{id}}",
    "type: archive",
    "title: {{title}}",
    "archive_kind: source",
    "source_path: local",
    "stored_path: source/example.txt",
    "compressed_path: example.txt.zip",
    "mime_type: text/plain",
    "byte_size: 0",
    "sha256: sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "compressed_sha256: sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "visibility: private",
    "provenance: manual",
    "ingest_status: pending",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
  rule: [
    "---",
    "id: {{id}}",
    "type: rule",
    "title: {{title}}",
    "tags: []",
    "owners: []",
    "links: []",
    "artifacts: []",
    "relates: []",
    "refs: []",
    "aliases: []",
    "created: {{created}}",
    "updated: {{updated}}",
    "---",
  ].join("\n"),
};

export function writeDefaultTemplates(root: string): void {
  for (const [name, content] of Object.entries(DEFAULT_TEMPLATES)) {
    writeFile(path.join(root, ".mdkg", "templates", "default", `${name}.md`), content);
  }
}
